name: Run tests without Docker 

on:
  workflow_dispatch: 

jobs:
    - name: Install python 
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -s -v